# fly.toml app configuration file generated for discord-vocabulary on 2026-04-28T01:09:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-vocabulary'
primary_region = 'nrt'

[build]